name: ChaosControl
main: com.gmail.buzziespy.ChaosControl.ChaosControl
version: 1.0

commands:
   givechaos:
      description: Gives player a Chaos Emerald
      usage: /givechaos
      permission: op
      permission-message: